package com.billgrim.server.database.model;

import java.io.Serializable;

public class Degree implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degree.id
     *
     * @mbg.generated Mon Nov 27 23:36:15 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column degree.degree
     *
     * @mbg.generated Mon Nov 27 23:36:15 CST 2017
     */
    private String degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table degree
     *
     * @mbg.generated Mon Nov 27 23:36:15 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degree.id
     *
     * @return the value of degree.id
     *
     * @mbg.generated Mon Nov 27 23:36:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degree.id
     *
     * @param id the value for degree.id
     *
     * @mbg.generated Mon Nov 27 23:36:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column degree.degree
     *
     * @return the value of degree.degree
     *
     * @mbg.generated Mon Nov 27 23:36:15 CST 2017
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column degree.degree
     *
     * @param degree the value for degree.degree
     *
     * @mbg.generated Mon Nov 27 23:36:15 CST 2017
     */
    public void setDegree(String degree) {
        this.degree = degree == null ? null : degree.trim();
    }
}