package com.billgrim.server.database.model;

import java.io.Serializable;

public class Image implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated Fri Dec 01 20:49:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.chinese_meaning_id
     *
     * @mbg.generated Fri Dec 01 20:49:30 CST 2017
     */
    private Integer chineseMeaningId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.url
     *
     * @mbg.generated Fri Dec 01 20:49:30 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table image
     *
     * @mbg.generated Fri Dec 01 20:49:30 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated Fri Dec 01 20:49:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated Fri Dec 01 20:49:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.chinese_meaning_id
     *
     * @return the value of image.chinese_meaning_id
     *
     * @mbg.generated Fri Dec 01 20:49:30 CST 2017
     */
    public Integer getChineseMeaningId() {
        return chineseMeaningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.chinese_meaning_id
     *
     * @param chineseMeaningId the value for image.chinese_meaning_id
     *
     * @mbg.generated Fri Dec 01 20:49:30 CST 2017
     */
    public void setChineseMeaningId(Integer chineseMeaningId) {
        this.chineseMeaningId = chineseMeaningId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.url
     *
     * @return the value of image.url
     *
     * @mbg.generated Fri Dec 01 20:49:30 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.url
     *
     * @param url the value for image.url
     *
     * @mbg.generated Fri Dec 01 20:49:30 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}