package com.billgrim.server.database.model;

import java.io.Serializable;

public class Prefix implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefix.id
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefix.prefix
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    private String prefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefix.chinese
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    private String chinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table prefix
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefix.id
     *
     * @return the value of prefix.id
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefix.id
     *
     * @param id the value for prefix.id
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefix.prefix
     *
     * @return the value of prefix.prefix
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefix.prefix
     *
     * @param prefix the value for prefix.prefix
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix == null ? null : prefix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefix.chinese
     *
     * @return the value of prefix.chinese
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefix.chinese
     *
     * @param chinese the value for prefix.chinese
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    public void setChinese(String chinese) {
        this.chinese = chinese == null ? null : chinese.trim();
    }
}