package com.billgrim.server.database.model;

import java.io.Serializable;

public class Root implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root.id
     *
     * @mbg.generated Tue Nov 28 01:47:56 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column root.root
     *
     * @mbg.generated Tue Nov 28 01:47:56 CST 2017
     */
    private String root;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table root
     *
     * @mbg.generated Tue Nov 28 01:47:56 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root.id
     *
     * @return the value of root.id
     *
     * @mbg.generated Tue Nov 28 01:47:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root.id
     *
     * @param id the value for root.id
     *
     * @mbg.generated Tue Nov 28 01:47:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column root.root
     *
     * @return the value of root.root
     *
     * @mbg.generated Tue Nov 28 01:47:56 CST 2017
     */
    public String getRoot() {
        return root;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column root.root
     *
     * @param root the value for root.root
     *
     * @mbg.generated Tue Nov 28 01:47:56 CST 2017
     */
    public void setRoot(String root) {
        this.root = root == null ? null : root.trim();
    }
}