package com.billgrim.server.database.model;

import java.io.Serializable;

public class Sort implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.id
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.sort
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    private String sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.chinese
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    private String chinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sort
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.id
     *
     * @return the value of sort.id
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.id
     *
     * @param id the value for sort.id
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.sort
     *
     * @return the value of sort.sort
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.sort
     *
     * @param sort the value for sort.sort
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.chinese
     *
     * @return the value of sort.chinese
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.chinese
     *
     * @param chinese the value for sort.chinese
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    public void setChinese(String chinese) {
        this.chinese = chinese == null ? null : chinese.trim();
    }
}