package com.billgrim.server.database.model;

import java.io.Serializable;

public class SpellSortGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_sort_group.id
     *
     * @mbg.generated Mon Nov 27 23:38:33 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_sort_group.spell_id
     *
     * @mbg.generated Mon Nov 27 23:38:33 CST 2017
     */
    private Integer spellId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_sort_group.sort_id
     *
     * @mbg.generated Mon Nov 27 23:38:33 CST 2017
     */
    private Integer sortId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spell_sort_group
     *
     * @mbg.generated Mon Nov 27 23:38:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_sort_group.id
     *
     * @return the value of spell_sort_group.id
     *
     * @mbg.generated Mon Nov 27 23:38:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_sort_group.id
     *
     * @param id the value for spell_sort_group.id
     *
     * @mbg.generated Mon Nov 27 23:38:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_sort_group.spell_id
     *
     * @return the value of spell_sort_group.spell_id
     *
     * @mbg.generated Mon Nov 27 23:38:33 CST 2017
     */
    public Integer getSpellId() {
        return spellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_sort_group.spell_id
     *
     * @param spellId the value for spell_sort_group.spell_id
     *
     * @mbg.generated Mon Nov 27 23:38:33 CST 2017
     */
    public void setSpellId(Integer spellId) {
        this.spellId = spellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_sort_group.sort_id
     *
     * @return the value of spell_sort_group.sort_id
     *
     * @mbg.generated Mon Nov 27 23:38:33 CST 2017
     */
    public Integer getSortId() {
        return sortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_sort_group.sort_id
     *
     * @param sortId the value for spell_sort_group.sort_id
     *
     * @mbg.generated Mon Nov 27 23:38:33 CST 2017
     */
    public void setSortId(Integer sortId) {
        this.sortId = sortId;
    }
}