package com.billgrim.server.database.model;

import java.io.Serializable;

public class SpellCategoryGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_category_group.id
     *
     * @mbg.generated Fri Dec 01 21:36:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_category_group.spell_id
     *
     * @mbg.generated Fri Dec 01 21:36:38 CST 2017
     */
    private Integer spellId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_category_group.category_id
     *
     * @mbg.generated Fri Dec 01 21:36:38 CST 2017
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spell_category_group
     *
     * @mbg.generated Fri Dec 01 21:36:38 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_category_group.id
     *
     * @return the value of spell_category_group.id
     *
     * @mbg.generated Fri Dec 01 21:36:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_category_group.id
     *
     * @param id the value for spell_category_group.id
     *
     * @mbg.generated Fri Dec 01 21:36:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_category_group.spell_id
     *
     * @return the value of spell_category_group.spell_id
     *
     * @mbg.generated Fri Dec 01 21:36:38 CST 2017
     */
    public Integer getSpellId() {
        return spellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_category_group.spell_id
     *
     * @param spellId the value for spell_category_group.spell_id
     *
     * @mbg.generated Fri Dec 01 21:36:38 CST 2017
     */
    public void setSpellId(Integer spellId) {
        this.spellId = spellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_category_group.category_id
     *
     * @return the value of spell_category_group.category_id
     *
     * @mbg.generated Fri Dec 01 21:36:38 CST 2017
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_category_group.category_id
     *
     * @param categoryId the value for spell_category_group.category_id
     *
     * @mbg.generated Fri Dec 01 21:36:38 CST 2017
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
}