package com.billgrim.server.database.model;

import java.io.Serializable;

public class SpellSuffixGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_suffix_group.id
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_suffix_group.spell_id
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    private Integer spellId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_suffix_group.suffix_id
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    private Integer suffixId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spell_suffix_group
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_suffix_group.id
     *
     * @return the value of spell_suffix_group.id
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_suffix_group.id
     *
     * @param id the value for spell_suffix_group.id
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_suffix_group.spell_id
     *
     * @return the value of spell_suffix_group.spell_id
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    public Integer getSpellId() {
        return spellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_suffix_group.spell_id
     *
     * @param spellId the value for spell_suffix_group.spell_id
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    public void setSpellId(Integer spellId) {
        this.spellId = spellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_suffix_group.suffix_id
     *
     * @return the value of spell_suffix_group.suffix_id
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    public Integer getSuffixId() {
        return suffixId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_suffix_group.suffix_id
     *
     * @param suffixId the value for spell_suffix_group.suffix_id
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    public void setSuffixId(Integer suffixId) {
        this.suffixId = suffixId;
    }
}