package com.billgrim.server.database.model;

import java.io.Serializable;

public class SpellPrefixGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_prefix_group.id
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_prefix_group.spell_id
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    private Integer spellId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spell_prefix_group.prefix_id
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    private Integer prefixId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table spell_prefix_group
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_prefix_group.id
     *
     * @return the value of spell_prefix_group.id
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_prefix_group.id
     *
     * @param id the value for spell_prefix_group.id
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_prefix_group.spell_id
     *
     * @return the value of spell_prefix_group.spell_id
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    public Integer getSpellId() {
        return spellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_prefix_group.spell_id
     *
     * @param spellId the value for spell_prefix_group.spell_id
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    public void setSpellId(Integer spellId) {
        this.spellId = spellId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spell_prefix_group.prefix_id
     *
     * @return the value of spell_prefix_group.prefix_id
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    public Integer getPrefixId() {
        return prefixId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spell_prefix_group.prefix_id
     *
     * @param prefixId the value for spell_prefix_group.prefix_id
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    public void setPrefixId(Integer prefixId) {
        this.prefixId = prefixId;
    }
}