package com.billgrim.server.database.model;

import java.io.Serializable;

public class Suffix implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suffix.id
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suffix.suffix
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column suffix.chinese
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    private String chinese;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table suffix
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suffix.id
     *
     * @return the value of suffix.id
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suffix.id
     *
     * @param id the value for suffix.id
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suffix.suffix
     *
     * @return the value of suffix.suffix
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suffix.suffix
     *
     * @param suffix the value for suffix.suffix
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column suffix.chinese
     *
     * @return the value of suffix.chinese
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    public String getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column suffix.chinese
     *
     * @param chinese the value for suffix.chinese
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    public void setChinese(String chinese) {
        this.chinese = chinese == null ? null : chinese.trim();
    }
}