package com.billgrim.server.database.mapper;

import com.billgrim.server.database.model.Meaning;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.ArrayList;
import java.util.List;

@Mapper
public interface MeaningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meaning
     *
     * @mbg.generated Mon Nov 27 23:37:15 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meaning
     *
     * @mbg.generated Mon Nov 27 23:37:15 CST 2017
     */
    int insert(Meaning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meaning
     *
     * @mbg.generated Mon Nov 27 23:37:15 CST 2017
     */
    int insertSelective(Meaning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meaning
     *
     * @mbg.generated Mon Nov 27 23:37:15 CST 2017
     */
    Meaning selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meaning
     *
     * @mbg.generated Mon Nov 27 23:37:15 CST 2017
     */
    int updateByPrimaryKeySelective(Meaning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meaning
     *
     * @mbg.generated Mon Nov 27 23:37:15 CST 2017
     */
    int updateByPrimaryKey(Meaning record);

    List<Meaning> selectBySpellIdAndSortId(@Param("spellId") Integer spellId, @Param("sortId") Integer sortId);

    List<Meaning> selectBySpellAndSortGroupId(@Param("groupId") Integer groupId);
}