package com.billgrim.server.database.mapper;

import com.billgrim.server.database.model.Prefix;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface PrefixMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefix
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefix
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    int insert(Prefix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefix
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    int insertSelective(Prefix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefix
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    Prefix selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefix
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    int updateByPrimaryKeySelective(Prefix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prefix
     *
     * @mbg.generated Mon Nov 27 23:37:02 CST 2017
     */
    int updateByPrimaryKey(Prefix record);

    Prefix selectByPrefix(String prefix);
}