package com.billgrim.server.database.mapper;

import com.billgrim.server.database.model.Root;
import org.apache.ibatis.annotations.Mapper;

import java.util.Optional;

@Mapper
public interface RootMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Tue Nov 28 01:47:56 CST 2017
     */
    int deleteByPrimaryKey(Root key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Tue Nov 28 01:47:56 CST 2017
     */
    int insert(Root record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table root
     *
     * @mbg.generated Tue Nov 28 01:47:56 CST 2017
     */
    int insertSelective(Root record);

    Root selectByPrimaryKey(Integer id);

    Root selectByRoot(String root);
}