package com.billgrim.server.database.mapper;

import com.billgrim.server.database.model.Sort;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    int insert(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    int insertSelective(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    Sort selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    int updateByPrimaryKeySelective(Sort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Mon Nov 27 23:35:39 CST 2017
     */
    int updateByPrimaryKey(Sort record);
}