package com.billgrim.server.database.mapper;

import com.billgrim.server.database.model.SpellPrefixGroup;
import com.billgrim.server.database.model.SpellSuffixGroup;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SpellPrefixGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_prefix_group
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_prefix_group
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    int insert(SpellPrefixGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_prefix_group
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    int insertSelective(SpellPrefixGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_prefix_group
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    SpellPrefixGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_prefix_group
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    int updateByPrimaryKeySelective(SpellPrefixGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_prefix_group
     *
     * @mbg.generated Fri Dec 01 21:37:22 CST 2017
     */
    int updateByPrimaryKey(SpellPrefixGroup record);

    List<SpellPrefixGroup> selectBySpellId(Integer spellId);

    List<SpellSuffixGroup> selectByPrefixId(Integer prefixId);
}