package com.billgrim.server.database.mapper;

import com.billgrim.server.database.model.SpellRootGroup;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SpellRootGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_root_group
     *
     * @mbg.generated Mon Nov 27 23:40:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_root_group
     *
     * @mbg.generated Mon Nov 27 23:40:18 CST 2017
     */
    int insert(SpellRootGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_root_group
     *
     * @mbg.generated Mon Nov 27 23:40:18 CST 2017
     */
    int insertSelective(SpellRootGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_root_group
     *
     * @mbg.generated Mon Nov 27 23:40:18 CST 2017
     */
    SpellRootGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_root_group
     *
     * @mbg.generated Mon Nov 27 23:40:18 CST 2017
     */
    int updateByPrimaryKeySelective(SpellRootGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_root_group
     *
     * @mbg.generated Mon Nov 27 23:40:18 CST 2017
     */
    int updateByPrimaryKey(SpellRootGroup record);
}