package com.billgrim.server.database.mapper;

import com.billgrim.server.database.model.Spell;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SpellMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell
     *
     * @mbg.generated Mon Nov 27 23:34:36 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell
     *
     * @mbg.generated Mon Nov 27 23:34:36 CST 2017
     */
    int insert(Spell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell
     *
     * @mbg.generated Mon Nov 27 23:34:36 CST 2017
     */
    int insertSelective(Spell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell
     *
     * @mbg.generated Mon Nov 27 23:34:36 CST 2017
     */
    Spell selectByPrimaryKey(Integer id);

    List<Spell> selectByPrimaryKeyList(List<Integer> idList);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell
     *
     * @mbg.generated Mon Nov 27 23:34:36 CST 2017
     */
    int updateByPrimaryKeySelective(Spell record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell
     *
     * @mbg.generated Mon Nov 27 23:34:36 CST 2017
     */
    int updateByPrimaryKey(Spell record);

    Spell selectBySpell(String spell);

    List<Spell> getSpellList();

    List<Spell> selectByRootId(Integer rootId);
}