package com.billgrim.server.database.mapper;

import com.billgrim.server.database.model.SpellSuffixGroup;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface SpellSuffixGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_suffix_group
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_suffix_group
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    int insert(SpellSuffixGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_suffix_group
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    int insertSelective(SpellSuffixGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_suffix_group
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    SpellSuffixGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_suffix_group
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    int updateByPrimaryKeySelective(SpellSuffixGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spell_suffix_group
     *
     * @mbg.generated Sat Dec 02 03:33:05 CST 2017
     */
    int updateByPrimaryKey(SpellSuffixGroup record);

    List<SpellSuffixGroup> selectBySpellId(Integer spellId);

    List<SpellSuffixGroup> selectBySuffixId(Integer suffixId);
}