package com.billgrim.server.database.mapper;

import com.billgrim.server.database.model.Prefix;
import com.billgrim.server.database.model.Suffix;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface SuffixMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suffix
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suffix
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    int insert(Suffix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suffix
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    int insertSelective(Suffix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suffix
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    Suffix selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suffix
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    int updateByPrimaryKeySelective(Suffix record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table suffix
     *
     * @mbg.generated Mon Nov 27 23:36:53 CST 2017
     */
    int updateByPrimaryKey(Suffix record);

    Suffix selectBySuffix(String suffix);
}